# Generated by Django 4.0.4 on 2022-06-12 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='l_name',
        ),
        migrations.CreateModel(
            name='Business_idaea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideas', models.TextField(max_length=256)),
                ('cost', models.IntegerField(max_length=512)),
                ('idea_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='ideas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.business_idaea'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
