# Generated by Django 4.0.4 on 2022-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_comment_f_name_remove_comment_l_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_idaea',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
