# Generated by Django 4.0.4 on 2022-06-12 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0004_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='oferts',
            new_name='offers',
        ),
        migrations.AddField(
            model_name='offers',
            name='idea_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offers',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.comment'),
        ),
    ]
