# Generated by Django 4.0.4 on 2022-06-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_rename_oferts_offers_offers_offers_idea_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='idea_owner',
        ),
    ]
