# Generated by Django 4.0.4 on 2022-06-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_remove_offers_idea_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_idaea',
            options={'verbose_name': 'ideas'},
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='offers',
            new_name='offers_state',
        ),
        migrations.AlterModelTable(
            name='business_idaea',
            table='ideas_business_idaea',
        ),
    ]
